// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type DegreeDocumentDataSlicesSlice = DegreeSlice;

/**
 * Content for Degree documents
 */
interface DegreeDocumentData {
  /**
   * name field in *Degree*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: degree.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Slice Zone field in *Degree*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: degree.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<DegreeDocumentDataSlicesSlice>;
}

/**
 * Degree document from Prismic
 *
 * - **API ID**: `degree`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DegreeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<DegreeDocumentData>, "degree", Lang>;

type FooterDocumentDataSlicesSlice = NavigationSlice | SocialsSlice;

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Slice Zone field in *Footer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FooterDocumentDataSlicesSlice>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<FooterDocumentData>, "footer", Lang>;

type NavigationDocumentDataSlicesSlice = NavigationItemSlice;

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Name field in *Navigation*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * title field in *Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Navigation*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NavigationDocumentDataSlicesSlice>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | FloatingTextSlice
  | BlogSlice
  | ProjectsSlice
  | DegreeSectionSlice
  | StackJourneySlice
  | CareerSectionSlice
  | SocialsSlice
  | HeroSectionSlice
  | RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type PrpjectsDocumentDataSlicesSlice = ProjectSlice;

/**
 * Content for Projects documents
 */
interface PrpjectsDocumentData {
  /**
   * Slice Zone field in *Projects*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: prpjects.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PrpjectsDocumentDataSlicesSlice>;
}

/**
 * Projects document from Prismic
 *
 * - **API ID**: `prpjects`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PrpjectsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PrpjectsDocumentData>,
    "prpjects",
    Lang
  >;

type SkillDocumentDataSlicesSlice = CarrerSlice;

/**
 * Content for Career documents
 */
interface SkillDocumentData {
  /**
   * name field in *Career*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skill.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Slice Zone field in *Career*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: skill.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SkillDocumentDataSlicesSlice>;
}

/**
 * Career document from Prismic
 *
 * - **API ID**: `skill`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SkillDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<SkillDocumentData>, "skill", Lang>;

export type AllDocumentTypes =
  | DegreeDocument
  | FooterDocument
  | NavigationDocument
  | PageDocument
  | PrpjectsDocument
  | SkillDocument;

/**
 * Primary content in *Blog → Default → Primary*
 */
export interface BlogSliceDefaultPrimary {
  /**
   * Title field in *Blog → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * link field in *Blog → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for Blog Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Blog*
 */
type BlogSliceVariation = BlogSliceDefault;

/**
 * Blog Shared Slice
 *
 * - **API ID**: `blog`
 * - **Description**: Blog
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogSlice = prismic.SharedSlice<"blog", BlogSliceVariation>;

/**
 * Primary content in *CareerSection → Default → Primary*
 */
export interface CareerSectionSliceDefaultPrimary {
  /**
   * title field in *CareerSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: career_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Default variation for CareerSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CareerSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CareerSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CareerSection*
 */
type CareerSectionSliceVariation = CareerSectionSliceDefault;

/**
 * CareerSection Shared Slice
 *
 * - **API ID**: `career_section`
 * - **Description**: CareerSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CareerSectionSlice = prismic.SharedSlice<
  "career_section",
  CareerSectionSliceVariation
>;

/**
 * Item in *Carrer → Default → Primary → skills*
 */
export interface CarrerSliceDefaultPrimarySkillsItem {
  /**
   * skill field in *Carrer → Default → Primary → skills*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: carrer.default.primary.skills[].skill
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  skill: prismic.SelectField<
    | "react"
    | "next"
    | "javascript"
    | "PHP"
    | "html"
    | "css"
    | "figma"
    | "prestashop"
    | "contao"
    | "tailwind"
    | "adobeXD"
    | "illustrator"
    | "dato"
    | "drupal"
    | "flutter"
    | "github"
    | "ionic"
    | "laravel"
    | "neltifly"
    | "photoshop"
    | "strapi"
    | "swift"
    | "symfony"
    | "typescript"
    | "vercel"
    | "vue"
    | "wordpress"
    | "payload"
    | "apiplatform"
    | "docker"
    | "prismic"
    | "hono"
    | "OPQUAST"
    | "mongoDB"
    | "mySQL"
    | "firebase"
    | "directus"
    | "cohere"
    | "imdb"
    | "nextauth"
    | "api"
    | "express"
    | "scss"
  >;
}

/**
 * Primary content in *Carrer → Default → Primary*
 */
export interface CarrerSliceDefaultPrimary {
  /**
   * date field in *Carrer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carrer.default.primary.date
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  date: prismic.KeyTextField;

  /**
   * job title field in *Carrer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carrer.default.primary.job_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  job_title: prismic.KeyTextField;

  /**
   * job status field in *Carrer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carrer.default.primary.job_status
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  job_status: prismic.KeyTextField;

  /**
   * company field in *Carrer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carrer.default.primary.company
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company: prismic.KeyTextField;

  /**
   * location field in *Carrer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carrer.default.primary.location
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  location: prismic.KeyTextField;

  /**
   * skills field in *Carrer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: carrer.default.primary.skills[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  skills: prismic.GroupField<Simplify<CarrerSliceDefaultPrimarySkillsItem>>;
}

/**
 * Default variation for Carrer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarrerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CarrerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Carrer*
 */
type CarrerSliceVariation = CarrerSliceDefault;

/**
 * Carrer Shared Slice
 *
 * - **API ID**: `carrer`
 * - **Description**: Carrer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarrerSlice = prismic.SharedSlice<"carrer", CarrerSliceVariation>;

/**
 * Item in *Degree → Default → Primary → skills*
 */
export interface DegreeSliceDefaultPrimarySkillsItem {
  /**
   * skill field in *Degree → Default → Primary → skills*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: degree.default.primary.skills[].skill
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  skill: prismic.SelectField<"OPQUAST" | "2">;
}

/**
 * Primary content in *Degree → Default → Primary*
 */
export interface DegreeSliceDefaultPrimary {
  /**
   * date field in *Degree → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: degree.default.primary.date
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  date: prismic.KeyTextField;

  /**
   * Intitule field in *Degree → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: degree.default.primary.intitule
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  intitule: prismic.KeyTextField;

  /**
   * is certification field in *Degree → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: degree.default.primary.is_certification
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_certification: prismic.BooleanField;

  /**
   * Certification desc field in *Degree → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: degree.default.primary.certification_desc
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  certification_desc: prismic.KeyTextField;

  /**
   * School field in *Degree → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: degree.default.primary.school
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  school: prismic.KeyTextField;

  /**
   * skills field in *Degree → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: degree.default.primary.skills[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  skills: prismic.GroupField<Simplify<DegreeSliceDefaultPrimarySkillsItem>>;
}

/**
 * Default variation for Degree Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DegreeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DegreeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Degree*
 */
type DegreeSliceVariation = DegreeSliceDefault;

/**
 * Degree Shared Slice
 *
 * - **API ID**: `degree`
 * - **Description**: Degree
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DegreeSlice = prismic.SharedSlice<"degree", DegreeSliceVariation>;

/**
 * Primary content in *DegreeSection → Default → Primary*
 */
export interface DegreeSectionSliceDefaultPrimary {
  /**
   * Title field in *DegreeSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: degree_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Default variation for DegreeSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DegreeSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DegreeSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *DegreeSection*
 */
type DegreeSectionSliceVariation = DegreeSectionSliceDefault;

/**
 * DegreeSection Shared Slice
 *
 * - **API ID**: `degree_section`
 * - **Description**: DegreeSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DegreeSectionSlice = prismic.SharedSlice<
  "degree_section",
  DegreeSectionSliceVariation
>;

/**
 * Primary content in *FloatingText → Default → Primary*
 */
export interface FloatingTextSliceDefaultPrimary {
  /**
   * Text field in *FloatingText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: floating_text.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for FloatingText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FloatingTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FloatingTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FloatingText*
 */
type FloatingTextSliceVariation = FloatingTextSliceDefault;

/**
 * FloatingText Shared Slice
 *
 * - **API ID**: `floating_text`
 * - **Description**: FloatingText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FloatingTextSlice = prismic.SharedSlice<
  "floating_text",
  FloatingTextSliceVariation
>;

/**
 * Item in *HeroSection → Default → Primary → socials*
 */
export interface HeroSectionSliceDefaultPrimarySocialsItem {
  /**
   * id_social field in *HeroSection → Default → Primary → socials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.socials[].id_social
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  id_social: prismic.KeyTextField;

  /**
   * link field in *HeroSection → Default → Primary → socials*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.socials[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * counter field in *HeroSection → Default → Primary → socials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.socials[].counter
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  counter: prismic.KeyTextField;

  /**
   * title popup field in *HeroSection → Default → Primary → socials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.socials[].title_popup
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_popup: prismic.KeyTextField;

  /**
   * desc popup field in *HeroSection → Default → Primary → socials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.socials[].desc_popup
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  desc_popup: prismic.KeyTextField;

  /**
   * qrcode field in *HeroSection → Default → Primary → socials*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.socials[].qrcode
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  qrcode: prismic.ImageField<never>;

  /**
   * Image resume field in *HeroSection → Default → Primary → socials*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.socials[].image_resume
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_resume: prismic.ImageField<never>;
}

/**
 * Primary content in *HeroSection → Default → Primary*
 */
export interface HeroSectionSliceDefaultPrimary {
  /**
   * profil field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.profil
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  profil: prismic.ImageField<never>;

  /**
   * status field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.status
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  status: prismic.KeyTextField;

  /**
   * Text field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * socials field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.socials[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  socials: prismic.GroupField<
    Simplify<HeroSectionSliceDefaultPrimarySocialsItem>
  >;
}

/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSection*
 */
type HeroSectionSliceVariation = HeroSectionSliceDefault;

/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: HeroSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSlice = prismic.SharedSlice<
  "hero_section",
  HeroSectionSliceVariation
>;

/**
 * Item in *Navigation → Default → Primary → Links*
 */
export interface NavigationSliceDefaultPrimaryLinksItem {
  /**
   * link field in *Navigation → Default → Primary → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.default.primary.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Primary content in *Navigation → Default → Primary*
 */
export interface NavigationSliceDefaultPrimary {
  /**
   * title field in *Navigation → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Links field in *Navigation → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.default.primary.links[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<NavigationSliceDefaultPrimaryLinksItem>>;
}

/**
 * Default variation for Navigation Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavigationSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Navigation*
 */
type NavigationSliceVariation = NavigationSliceDefault;

/**
 * Navigation Shared Slice
 *
 * - **API ID**: `navigation`
 * - **Description**: Navigation
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationSlice = prismic.SharedSlice<
  "navigation",
  NavigationSliceVariation
>;

/**
 * Primary content in *NavigationItem → Default → Primary*
 */
export interface NavigationItemSliceDefaultPrimary {
  /**
   * link field in *NavigationItem → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_item.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for NavigationItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavigationItemSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NavigationItem*
 */
type NavigationItemSliceVariation = NavigationItemSliceDefault;

/**
 * NavigationItem Shared Slice
 *
 * - **API ID**: `navigation_item`
 * - **Description**: NavigationItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationItemSlice = prismic.SharedSlice<
  "navigation_item",
  NavigationItemSliceVariation
>;

/**
 * Item in *Project → Default → Primary → skills*
 */
export interface ProjectSliceDefaultPrimarySkillsItem {
  /**
   * skill field in *Project → Default → Primary → skills*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: project.default.primary.skills[].skill
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  skill: prismic.SelectField<
    | "react"
    | "next"
    | "javascript"
    | "PHP"
    | "html"
    | "css"
    | "figma"
    | "prestashop"
    | "contao"
    | "tailwind"
    | "adobeXD"
    | "illustrator"
    | "dato"
    | "drupal"
    | "flutter"
    | "github"
    | "ionic"
    | "laravel"
    | "neltifly"
    | "photoshop"
    | "strapi"
    | "swift"
    | "symfony"
    | "typescript"
    | "vercel"
    | "vue"
    | "wordpress"
    | "payload"
    | "apiplatform"
    | "docker"
    | "prismic"
    | "hono"
    | "OPQUAST"
    | "mongoDB"
    | "mySQL"
    | "firebase"
    | "directus"
    | "cohere"
    | "imdb"
    | "nextauth"
    | "api"
    | "express"
    | "scss"
  >;
}

/**
 * Item in *Project → Default → Primary → images*
 */
export interface ProjectSliceDefaultPrimaryImagesItem {
  /**
   * image field in *Project → Default → Primary → images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *Project → Default → Primary*
 */
export interface ProjectSliceDefaultPrimary {
  /**
   * title field in *Project → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * custom class field in *Project → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.default.primary.custom_class
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  custom_class: prismic.KeyTextField;

  /**
   * Description field in *Project → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * repo git field in *Project → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: project.default.primary.repo_git
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  repo_git: prismic.LinkField;

  /**
   * url field in *Project → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: project.default.primary.url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField;

  /**
   * skills field in *Project → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project.default.primary.skills[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  skills: prismic.GroupField<Simplify<ProjectSliceDefaultPrimarySkillsItem>>;

  /**
   * images field in *Project → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<Simplify<ProjectSliceDefaultPrimaryImagesItem>>;
}

/**
 * Default variation for Project Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Project*
 */
type ProjectSliceVariation = ProjectSliceDefault;

/**
 * Project Shared Slice
 *
 * - **API ID**: `project`
 * - **Description**: Project
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectSlice = prismic.SharedSlice<
  "project",
  ProjectSliceVariation
>;

/**
 * Primary content in *Projects → Default → Primary*
 */
export interface ProjectsSliceDefaultPrimary {
  /**
   * Title field in *Projects → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Default variation for Projects Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Projects*
 */
type ProjectsSliceVariation = ProjectsSliceDefault;

/**
 * Projects Shared Slice
 *
 * - **API ID**: `projects`
 * - **Description**: Projects
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectsSlice = prismic.SharedSlice<
  "projects",
  ProjectsSliceVariation
>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Item in *Socials → Default → Primary → social*
 */
export interface SocialsSliceDefaultPrimarySocialItem {
  /**
   * id_social field in *Socials → Default → Primary → social*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: socials.default.primary.social[].id_social
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  id_social: prismic.KeyTextField;

  /**
   * link field in *Socials → Default → Primary → social*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: socials.default.primary.social[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Primary content in *Socials → Default → Primary*
 */
export interface SocialsSliceDefaultPrimary {
  /**
   * Title field in *Socials → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: socials.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * social field in *Socials → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: socials.default.primary.social[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social: prismic.GroupField<Simplify<SocialsSliceDefaultPrimarySocialItem>>;
}

/**
 * Default variation for Socials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SocialsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Socials*
 */
type SocialsSliceVariation = SocialsSliceDefault;

/**
 * Socials Shared Slice
 *
 * - **API ID**: `socials`
 * - **Description**: Socials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialsSlice = prismic.SharedSlice<
  "socials",
  SocialsSliceVariation
>;

/**
 * Item in *StackJourney → Default → Primary → skills favorite*
 */
export interface StackJourneySliceDefaultPrimarySkillsItem {
  /**
   * skill field in *StackJourney → Default → Primary → skills favorite*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: stack_journey.default.primary.skills[].skill
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  skill: prismic.SelectField<
    | "react"
    | "next"
    | "javascript"
    | "PHP"
    | "html"
    | "css"
    | "figma"
    | "prestashop"
    | "contao"
    | "tailwind"
    | "adobeXD"
    | "illustrator"
    | "dato"
    | "drupal"
    | "flutter"
    | "github"
    | "ionic"
    | "laravel"
    | "neltifly"
    | "photoshop"
    | "strapi"
    | "swift"
    | "symfony"
    | "typescript"
    | "vercel"
    | "vue"
    | "wordpress"
    | "payload"
    | "apiplatform"
    | "docker"
    | "prismic"
    | "hono"
    | "OPQUAST"
    | "mongoDB"
    | "mySQL"
    | "firebase"
    | "directus"
    | "cohere"
    | "imdb"
    | "nextauth"
    | "api"
    | "express"
    | "scss"
  >;
}

/**
 * Item in *StackJourney → Default → Primary → skills next*
 */
export interface StackJourneySliceDefaultPrimarySkillsNextItem {
  /**
   * skill field in *StackJourney → Default → Primary → skills next*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: stack_journey.default.primary.skills_next[].skill
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  skill: prismic.SelectField<
    | "react"
    | "next"
    | "javascript"
    | "PHP"
    | "html"
    | "css"
    | "figma"
    | "prestashop"
    | "contao"
    | "tailwind"
    | "adobeXD"
    | "illustrator"
    | "dato"
    | "drupal"
    | "flutter"
    | "github"
    | "ionic"
    | "laravel"
    | "neltifly"
    | "photoshop"
    | "strapi"
    | "swift"
    | "symfony"
    | "typescript"
    | "vercel"
    | "vue"
    | "wordpress"
    | "payload"
    | "apiplatform"
    | "docker"
    | "prismic"
    | "hono"
    | "OPQUAST"
    | "mongoDB"
    | "mySQL"
    | "firebase"
    | "directus"
    | "cohere"
    | "imdb"
    | "nextauth"
    | "api"
    | "express"
    | "scss"
  >;
}

/**
 * Item in *StackJourney → Default → Primary → skills other*
 */
export interface StackJourneySliceDefaultPrimarySkillsOtherItem {
  /**
   * skill field in *StackJourney → Default → Primary → skills other*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: stack_journey.default.primary.skills_other[].skill
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  skill: prismic.SelectField<
    | "react"
    | "next"
    | "javascript"
    | "PHP"
    | "html"
    | "css"
    | "figma"
    | "prestashop"
    | "contao"
    | "tailwind"
    | "adobeXD"
    | "illustrator"
    | "dato"
    | "drupal"
    | "flutter"
    | "github"
    | "ionic"
    | "laravel"
    | "neltifly"
    | "photoshop"
    | "strapi"
    | "swift"
    | "symfony"
    | "typescript"
    | "vercel"
    | "vue"
    | "wordpress"
    | "payload"
    | "apiplatform"
    | "docker"
    | "prismic"
    | "hono"
    | "OPQUAST"
    | "mongoDB"
    | "mySQL"
    | "firebase"
    | "directus"
    | "cohere"
    | "imdb"
    | "nextauth"
    | "api"
    | "express"
    | "scss"
  >;
}

/**
 * Primary content in *StackJourney → Default → Primary*
 */
export interface StackJourneySliceDefaultPrimary {
  /**
   * favorite stack field in *StackJourney → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stack_journey.default.primary.favorite_stack
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  favorite_stack: prismic.RichTextField;

  /**
   * skills favorite field in *StackJourney → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: stack_journey.default.primary.skills[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  skills: prismic.GroupField<
    Simplify<StackJourneySliceDefaultPrimarySkillsItem>
  >;

  /**
   * next stack field in *StackJourney → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stack_journey.default.primary.next_stack
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  next_stack: prismic.RichTextField;

  /**
   * skills next field in *StackJourney → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: stack_journey.default.primary.skills_next[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  skills_next: prismic.GroupField<
    Simplify<StackJourneySliceDefaultPrimarySkillsNextItem>
  >;

  /**
   * other field in *StackJourney → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stack_journey.default.primary.other
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  other: prismic.RichTextField;

  /**
   * skills other field in *StackJourney → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: stack_journey.default.primary.skills_other[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  skills_other: prismic.GroupField<
    Simplify<StackJourneySliceDefaultPrimarySkillsOtherItem>
  >;
}

/**
 * Default variation for StackJourney Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StackJourneySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StackJourneySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *StackJourney*
 */
type StackJourneySliceVariation = StackJourneySliceDefault;

/**
 * StackJourney Shared Slice
 *
 * - **API ID**: `stack_journey`
 * - **Description**: StackJourney
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StackJourneySlice = prismic.SharedSlice<
  "stack_journey",
  StackJourneySliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      DegreeDocument,
      DegreeDocumentData,
      DegreeDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataSlicesSlice,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PrpjectsDocument,
      PrpjectsDocumentData,
      PrpjectsDocumentDataSlicesSlice,
      SkillDocument,
      SkillDocumentData,
      SkillDocumentDataSlicesSlice,
      AllDocumentTypes,
      BlogSlice,
      BlogSliceDefaultPrimary,
      BlogSliceVariation,
      BlogSliceDefault,
      CareerSectionSlice,
      CareerSectionSliceDefaultPrimary,
      CareerSectionSliceVariation,
      CareerSectionSliceDefault,
      CarrerSlice,
      CarrerSliceDefaultPrimarySkillsItem,
      CarrerSliceDefaultPrimary,
      CarrerSliceVariation,
      CarrerSliceDefault,
      DegreeSlice,
      DegreeSliceDefaultPrimarySkillsItem,
      DegreeSliceDefaultPrimary,
      DegreeSliceVariation,
      DegreeSliceDefault,
      DegreeSectionSlice,
      DegreeSectionSliceDefaultPrimary,
      DegreeSectionSliceVariation,
      DegreeSectionSliceDefault,
      FloatingTextSlice,
      FloatingTextSliceDefaultPrimary,
      FloatingTextSliceVariation,
      FloatingTextSliceDefault,
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimarySocialsItem,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
      NavigationSlice,
      NavigationSliceDefaultPrimaryLinksItem,
      NavigationSliceDefaultPrimary,
      NavigationSliceVariation,
      NavigationSliceDefault,
      NavigationItemSlice,
      NavigationItemSliceDefaultPrimary,
      NavigationItemSliceVariation,
      NavigationItemSliceDefault,
      ProjectSlice,
      ProjectSliceDefaultPrimarySkillsItem,
      ProjectSliceDefaultPrimaryImagesItem,
      ProjectSliceDefaultPrimary,
      ProjectSliceVariation,
      ProjectSliceDefault,
      ProjectsSlice,
      ProjectsSliceDefaultPrimary,
      ProjectsSliceVariation,
      ProjectsSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      SocialsSlice,
      SocialsSliceDefaultPrimarySocialItem,
      SocialsSliceDefaultPrimary,
      SocialsSliceVariation,
      SocialsSliceDefault,
      StackJourneySlice,
      StackJourneySliceDefaultPrimarySkillsItem,
      StackJourneySliceDefaultPrimarySkillsNextItem,
      StackJourneySliceDefaultPrimarySkillsOtherItem,
      StackJourneySliceDefaultPrimary,
      StackJourneySliceVariation,
      StackJourneySliceDefault,
    };
  }
}
